INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-01', 'HC Manhã', 'HC manha', 1, 1, 'HC manha', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-01', 'Zona Norte (Manhã)', '7-19 troca com a Lygia !!!', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-02', 'Noturno (19-07)', 'Noturno ZN melissa fixo mari grupo sexta 11/11', 1, 1, 'Noturno ZN melissa fixo mari grupo sexta 11/11', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-02', 'Zona Norte (Manhã)', 'Manhã maicon passei Lygia', 1, 1, 'Manhã maicon passei Lygia', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-03', 'Apoio (19-01)', 'Marco Antônio 03/11 fiz apoio', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-04', 'Zona Norte (Manhã)', 'ZN Manhã camila manha', 1, 1, 'ZN Manhã camila manha', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-04', 'Noturno (19-07)', 'Noturno ZN amanda noturno 02/11 Carlos', 1, 1, 'Noturno ZN amanda noturno 02/11 Carlos', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-05', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-06', 'Zona Norte (Tarde)', 'Tarde Igor', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-06', 'Zona Norte (Tarde)', 'ZN 13-19 fixo juh', 1, 1, 'ZN 13-19 fixo juh', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-07', 'Zona Norte (Manhã)', 'Manhã mari pvd 04/01', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-07', 'Noturno (19-07)', 'Noturno jédsica pvd 03/11 amanda pvd 07/01', 1, 1, 'Noturno jédsica pvd 03/11 amanda pvd 07/01', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-08', 'Zona Norte (Manhã)', 'Passei Matheus', 1, 1, 'Passei Matheus', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-08', 'Zona Norte (Manhã)', 'Manhã Yana pvd 07/01', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-08', 'Zona Norte (Tarde)', 'ZN 13-19 pascoal', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-08', 'Noturno (19-07)', 'Noturno ZN fixo da lygia patricia', 1, 1, 'Noturno ZN fixo da lygia patricia', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-09', 'Noturno (19-07)', 'Noturno ZN melissa fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-09', 'Zona Norte (Manhã)', 'Manhã juh, 08/01, original thiagopassei juh', 1, 1, 'Manhã juh, 08/01, original thiagopassei juh', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-10', 'Zona Norte (Manhã)', 'Manhã 2° sabado fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-10', 'Noturno (19-07)', 'Noturno origirinal bruna', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-11', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-12', 'Pessoal', 'Samila', 0, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-13', 'HC Manhã', 'HC manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-13', 'Zona Norte (Tarde)', 'ZN 13-19 fixo passei pascoal', 1, 1, 'ZN 13-19 fixo passei pascoal', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-14', 'HC Manhã', 'HC manha romerson', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-14', 'Zona Norte (Tarde)', 'Tarde pessoal marcos', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-15', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-15', 'Noturno (19-07)', 'Noturno ZN fixo da lygia', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-16', 'Noturno (19-07)', 'Noturno ZN melissa fixo confirmar trcoa sabado maria', 1, 1, 'Noturno ZN melissa fixo confirmar trcoa sabado maria', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-17', 'Zona Norte (Manhã)', 'Manhã maria fernanda a confirmar', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-18', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-19', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-20', 'HC Manhã', 'HC manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-20', 'Zona Norte (Tarde)', 'ZN 13-19 fixo juh', 1, 1, 'ZN 13-19 fixo juh', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-21', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-22', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-22', 'Zona Norte (Manhã)', 'Passei fixo patricia', 1, 1, 'Passei fixo patricia', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-23', 'Noturno (19-07)', 'Noturno ZN melissa fixo allna', 1, 1, 'Noturno ZN melissa fixo allna', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-23', 'Zona Norte (Manhã)', 'Manhã Juh Hammes', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-24', 'Pessoal', 'Formatura', 0, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-24', 'Noturno (19-07)', 'Noturno origirinal bruna Mari confirmado', 1, 1, 'Noturno origirinal bruna Mari confirmado', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-25', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-25', 'Zona Norte (Tarde)', 'Tarde pascoal', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-26', 'Pessoal', 'Nutri 16:45', 0, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-27', 'HC Manhã', 'HC manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-27', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-29', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-29', 'Zona Norte (Tarde)', 'ZN 13-19 pascoal', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-30', 'Apoio (19-01)', 'Fixo 5 sexta apoio lais', 1, 1, 'Fixo 5 sexta apoio lais', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-01-30', 'Noturno (19-07)', 'Noturno origirinal bruna allana', 1, 1, 'Noturno origirinal bruna allana', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-01', 'Zona Norte (Manhã)', 'ZN Manhã maickon grupo 06/01', 1, 1, 'ZN Manhã maickon grupo 06/01', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-02', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-03', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-04', 'Zona Norte (Tarde)', 'Tarde pascoal', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-05', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-06', 'Noturno (19-07)', 'Noturno fixo ainda 1 sexta', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-08', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-10', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-11', 'Zona Norte (Manhã)', 'Manhã mari pvd 15/12', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-12', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-12', 'Noturno (19-07)', 'Noturno origirinal mari troca', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-14', 'Zona Norte (Manhã)', 'Manhã 2° sabado fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-14', 'Noturno (19-07)', 'Oferecer noturno miriam', 0, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-14', 'Noturno (19-07)', 'Noturno origirinal bruna', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-15', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-16', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-17', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-18', 'Zona Norte (Manhã)', 'Manhã mari pvd 15/12', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-18', 'Zona Norte (Tarde)', 'ZN 13-19 paula pvd 06/01', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-19', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-21', 'Zona Norte (Manhã)', 'Manhã plantao maria a confirmar', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-21', 'Zona Norte (Manhã)', 'Possivel plantao maria', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-22', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-24', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-26', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-02-28', 'Noturno (19-07)', 'Noturno origirinal troquei mari por 12/02', 1, 1, 'Noturno origirinal troquei mari por 12/02', 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-01', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-02', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-03', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-05', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-06', 'Noturno (19-07)', 'Noturno fixo ainda 1 sexta', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-08', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-10', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-12', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-14', 'Zona Norte (Manhã)', 'Manhã 2° sabado fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-14', 'Noturno (19-07)', 'Noturno origirinal bruna', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-15', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-16', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-17', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-19', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-21', 'Zona Norte (Manhã)', '3° sabado manhã fixo maria fernanda', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-22', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-24', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-26', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-28', 'Noturno (19-07)', 'Noturno origirinal bruna', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-29', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-30', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-03-31', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-02', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-03', 'Noturno (19-07)', 'Noturno fixo ainda 1 sexta', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-05', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-07', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-09', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-11', 'Zona Norte (Manhã)', 'Manhã 2° sabado fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-11', 'Zona Norte (Manhã)', 'Preencher mais 2 e 4 sabado da bruna', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-11', 'Noturno (19-07)', 'Noturno origirinal bruna', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-12', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-13', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-14', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-16', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-18', 'Zona Norte (Manhã)', '3° sabado manhã fixo maria fernanda', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-19', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-21', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-23', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-26', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-27', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-28', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-04-30', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-01', 'Noturno (19-07)', 'Noturno fixo ainda 1 sexta', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-03', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-05', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-07', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-09', 'Zona Norte (Manhã)', 'Manhã 2° sabado fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-10', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-11', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-12', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-14', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-16', 'Zona Norte (Manhã)', '3° sabado manhã fixo maria fernanda', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-17', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-19', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-21', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-24', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-25', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-26', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-28', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-29', 'Zona Norte (Manhã)', 'Fixo 5ª sexta 19-01', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-30', 'Zona Norte (Manhã)', 'Fixo 5ª sabado manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-05-31', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-02', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-04', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-05', 'Noturno (19-07)', 'Noturno fixo ainda 1 sexta', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-07', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-08', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-09', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-11', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-13', 'Zona Norte (Manhã)', 'Manhã 2° sabado fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-14', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-16', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-18', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-20', 'Zona Norte (Manhã)', '3° sabado manhã fixo maria fernanda', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-21', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-22', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-23', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-25', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-28', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-06-30', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-02', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-03', 'Noturno (19-07)', 'Noturno fixo ainda 1 sexta', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-05', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-06', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-07', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-09', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-11', 'Zona Norte (Manhã)', 'Manhã 2° sabado fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-12', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-14', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-16', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-18', 'Zona Norte (Manhã)', '3° sabado manhã fixo maria fernanda', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-19', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-20', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-21', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-23', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-26', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-28', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-30', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-07-31', 'Apoio (19-01)', 'Fixo 5ª sexta Apoio', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-02', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-03', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-04', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-06', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-07', 'Noturno (19-07)', 'Noturno fixo ainda 1 sexta', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-08', 'Zona Norte (Manhã)', 'Manhã 2° sabado fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-09', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-11', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-11', 'Zona Norte (Manhã)', 'Cancelar Gemini', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-13', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-15', 'Zona Norte (Manhã)', '3° sabado manhã fixo maria fernanda', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-16', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-17', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-18', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-20', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-23', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-25', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-27', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-29', 'Zona Norte (Manhã)', 'Fixo 5ª sabado manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-30', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-08-31', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-01', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-03', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-04', 'Noturno (19-07)', 'Noturno fixo ainda 1 sexta', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-06', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-08', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-10', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-12', 'Zona Norte (Manhã)', 'Manhã 2° sabado fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-13', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-14', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-15', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-17', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-19', 'Zona Norte (Manhã)', '3° sabado manhã fixo maria fernanda', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-20', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-22', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-24', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-27', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-28', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-09-29', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-01', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-02', 'Noturno (19-07)', 'Noturno fixo ainda 1 sexta', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-04', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-06', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-08', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-10', 'Zona Norte (Manhã)', 'Manhã 2° sabado fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-11', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-12', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-13', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-15', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-17', 'Zona Norte (Manhã)', '3° sabado manhã fixo maria fernanda', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-18', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-20', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-22', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-25', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-26', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-27', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-29', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-30', 'Apoio (19-01)', 'Fixo 5ª sexta Apoio', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-10-31', 'Zona Norte (Manhã)', 'Fixo 5ª sabado manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-01', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-03', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-05', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-06', 'Noturno (19-07)', 'Noturno fixo ainda 1 sexta', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-08', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-09', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-10', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-12', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-14', 'Zona Norte (Manhã)', 'Manhã 2° sabado fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-15', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-17', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-19', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-21', 'Zona Norte (Manhã)', '3° sabado manhã fixo maria fernanda', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-22', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-23', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-24', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-26', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-11-29', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-01', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-03', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-04', 'Noturno (19-07)', 'Noturno fixo ainda 1 sexta', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-06', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-07', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-08', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-10', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-12', 'Zona Norte (Manhã)', 'Manhã 2° sabado fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-13', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-15', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-17', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-19', 'Zona Norte (Manhã)', '3° sabado manhã fixo maria fernanda', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-20', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-21', 'Zona Norte (Tarde)', 'Corredor tarde juh', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-22', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-24', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-27', 'Zona Norte (Manhã)', 'ZN Manhã', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-29', 'Zona Norte (Tarde)', 'ZN 13-19 fixo', 1, 0, NULL, 0);
INSERT INTO events (userId, date, type, description, isShift, isPassed, passedReason, isCancelled) VALUES (1, '2026-12-31', 'HC Manhã', 'HC manha', 1, 0, NULL, 0);